/*
-- Query: SELECT * FROM mysqldb.ptb_feed_tag
LIMIT 0, 1000

-- Date: 2025-12-03 11:25
*/
INSERT INTO `` (`FEED_TAG_NO`,`FEED_NO`,`TAG_NO`) VALUES (45,32,35);
INSERT INTO `` (`FEED_TAG_NO`,`FEED_NO`,`TAG_NO`) VALUES (46,33,36);
INSERT INTO `` (`FEED_TAG_NO`,`FEED_NO`,`TAG_NO`) VALUES (47,34,37);
INSERT INTO `` (`FEED_TAG_NO`,`FEED_NO`,`TAG_NO`) VALUES (48,34,38);
INSERT INTO `` (`FEED_TAG_NO`,`FEED_NO`,`TAG_NO`) VALUES (49,35,39);
INSERT INTO `` (`FEED_TAG_NO`,`FEED_NO`,`TAG_NO`) VALUES (50,35,40);
INSERT INTO `` (`FEED_TAG_NO`,`FEED_NO`,`TAG_NO`) VALUES (51,36,41);
INSERT INTO `` (`FEED_TAG_NO`,`FEED_NO`,`TAG_NO`) VALUES (52,37,42);
INSERT INTO `` (`FEED_TAG_NO`,`FEED_NO`,`TAG_NO`) VALUES (53,38,41);
INSERT INTO `` (`FEED_TAG_NO`,`FEED_NO`,`TAG_NO`) VALUES (54,38,43);
INSERT INTO `` (`FEED_TAG_NO`,`FEED_NO`,`TAG_NO`) VALUES (55,39,44);
