/*
-- Query: SELECT * FROM mysqldb.ptb_tag_list
LIMIT 0, 1000

-- Date: 2025-12-03 11:26
*/
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (34,'123');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (33,'2112');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (30,'df');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (17,'가');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (3,'개발');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (37,'개츠비');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (32,'과주');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (40,'관계');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (18,'나');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (39,'낚시');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (19,'다');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (2,'동기부여');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (20,'라');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (28,'로렘입숨');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (21,'마');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (36,'마음');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (22,'바');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (11,'바다');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (35,'변화');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (23,'사');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (31,'사과');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (27,'사사');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (41,'삶');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (14,'섬');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (1,'성장');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (44,'속담');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (4,'스포츠');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (29,'아무말');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (38,'아버지');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (43,'얽매임');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (5,'여');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (13,'여행');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (12,'음식');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (25,'자바');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (16,'자연');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (26,'잡아');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (42,'질문');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (24,'책');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (15,'해양');
INSERT INTO `` (`TAG_NO`,`TAG_NAME`) VALUES (6,'행');
